CREATE TABLE "co" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"co_name"	TEXT NOT NULL UNIQUE,
	"co_address"	TEXT NOT NULL
),
CREATE TABLE "companies" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"company_name"	TEXT NOT NULL UNIQUE,
	"company_type"	TEXT NOT NULL
),
CREATE TABLE "customers" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"customer_code"	TEXT NOT NULL UNIQUE,
	"customer_name"	TEXT NOT NULL,
	"co_id"	INTEGER
)